---
# tasks file for kubernetes_master
   
   - name: Make the Swap inactive
     command: swapoff -a
   - name: Remove Swap entry from /etc/fstab.
     lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent
   - name: Installing Prerequisites for Kubernetes
     apt: 
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - vim
         - software-properties-common
       state: present
   - name: Add Docker’s official GPG key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
   - name: Add Docker Repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
       state: present
       filename: docker
       mode: 0600
   - name: Install Docker Engine.
     apt: 
       name:
         - docker-ce
         - docker-ce-cli
         - containerd.io
       state: present
   - name: Enable service docker, and enable persistently
     service: 
       name: docker
       enabled: yes
   - name: Add Google official GPG key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
   - name: Add Kubernetes Repository
     apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
       state: present
       filename: kubernetes
       mode: 0600
   - name: Installing Kubernetes Cluster Packages.
     apt: 
       name:
         - kubeadm
         - kubectl
         - kubelet
       state: present
   - name: Enable service kubelet, and enable persistently
     service: 
       name: kubelet
       enabled: yes
   - name: Pulling Images using kubeadm
     shell: "kubeadm config  images pull"
     changed_when: false
   - name: copy daemon file
     copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
   - name: Restarting Docker
     service:
        name: docker
        state:  restarted
   - name: updating k8s config file
     copy:
       dest: /etc/sysctl.d/k8s.conf
       src: k8s.conf
   - name: restarting sysctl
     command: sysctl --system

   - name: Intilizing Kubernetes Cluster
     command: kubeadm init --pod-network-cidr 10.244.0.0/16  --control-plane-endpoint="{{ k8s_master_ip }}"
     run_once: true
   - name: Creating .kube directory
     file:
      name: "$HOME/.kube"
      state: directory

   - name: Copy kube config
     copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes

   - name: changing owner permission
     shell: "chown $(id -u):$(id -g) $HOME/.kube/config"

   - name: Flannel Command
     shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
     ignore_errors: yes



   - name: Get the token for joining the nodes with Kuberentes master.
     shell: kubeadm token create  --print-join-command
     register: kubernetes_join_command

   - debug:
       msg: "{{ kubernetes_join_command.stdout }}"

   - name: Copy join command to local file.
     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
